### ISSUE TITLE
RSS feed - no Atom

### ISSUE THREAD

**Issue by tverlaan** [lawik/beambloggers#11]
Currently only RSS feeds are supported, would you be open to a PR supporting RSS and Atom? We could use https://github.com/michaelnisi/feeder for this. It'll be a bit slower, but I'm not sure if that's crucial at the moment. Secondly it would remove the dependency on rust which should make it easier for people to contribute to this repo.

**Comment by lawik** [comment]
Happy to receive a PR. Very welcome. The RSS ingestion was pushed exactly so far that it worked for some sites and then I had other stuff I needed to do. I thought it would cover Atom as well but that would explain why I'm only getting some of these.

I have further thoughts on what to do with this data that could be fun but first it needs to manage pulling from most sites that expose a findable RSS/Atom feed.

**Comment by tverlaan** [comment]
Please check the PR :)

I'm not sure what you're planning but you're one step closer 😎

**Comment by lawik** [comment]
This was great! And now its up :) I fixed my broken scheduling of updates as well and made it sort the blog list by latest activity. Seems fair enough.

**Comment by tverlaan** [comment]
The only downside of that approach is for those that have no RSS feed or a broken RSS feed, they will always end up at the bottom.

**Comment by lawik** [comment]
Yeah, but it is a fixable problem on their end at least. Need to document it at some point.

This will also help with avoiding stale sites at the top. Which helps readers. 

Something to consider is to save a hash for the site front page and consider the site updated if that changes for sites that don't have an RSS feed.
